name: AzureKustoSpark
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: build
    permissions:
      checks: write
      pull-requests: write
      id-token: write
      contents: read      
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.APP_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            access_token=$(az account get-access-token --scope=${{ secrets.CLUSTER }}/.default --query accessToken -o tsv)
      - name: Check out code into the Spark module directory
        uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 8
          cache: 'maven'
      - name: Run the Maven verify phase
        env:
          kustoAadAuthorityID: ${{ secrets.TENANT_ID }}
          kustoDatabase: ${{ secrets.DATABASE }}
          kustoCluster: ${{ secrets.CLUSTER }}
          kustoAadAppId: ${{secrets.APP_ID}}
        run: mvn clean test verify -DkustoAadAppId=${{ secrets.APP_ID }} -DkustoAadAuthorityID=${{ secrets.TENANT_ID }} -DkustoDatabase=${{ secrets.DATABASE }} -DkustoCluster=${{ secrets.CLUSTER }} -DaccessToken=$access_token
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            connector/target/surefire-reports/*.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2